### ISSUE TITLE
Proposta de desafio #1

### ISSUE THREAD

**Issue by joaovitor644** [Felipemarinho18/Minha-evolu-o-em-JAVA-#1]
oi eu estou criando esse desafio (e outros) para testa seus conhecimentos em java

desafio 1:

Crie um programa que receba a altura e o peso do usuário e mostre para o mesmo o seu IMC.

**Comment by Felipemarinho18** [comment]
@joaovitor644 desafio concluido!! Resposta no arquivo AULA010.
